_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NMS_THRESH_TEST: 0.4
    SCORE_THRESH_TEST: 0.0001
OUTPUT_DIR: "./output/r50_wsdn"
