_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  MASK_ON: True
  BOX_CLS_ON: True
  BOX_REG_ON: True
  ROI_HEADS:
    IOU_THRESHOLDS: [0.1, 0.4, 0.6]
    IOU_LABELS: [-1, 0, -1, 1]
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
OUTPUT_DIR: "./output/r50_wsdn_mask_rcnn"
